services:
  db:
    image: mysql:8.0  # <-- MUITO IMPORTANTE: Fixar a versão
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: reparaai
      MYSQL_ROOT_PASSWORD: senha # <-- Esta é a única variável necessária para a senha do root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reparai-net

  backend:
    build: .
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - reparai-net

volumes:
  db_data:

networks:
  reparai-net:
    driver: bridge