version: '3.8'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: reparaai      # <-- Altere aqui
      MYSQL_USER: root
      MYSQL_PASSWORD: senha         # <-- Altere aqui
      MYSQL_ROOT_PASSWORD: senha    # <-- Altere aqui
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reparai-net

  backend:
    build: .
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db
    env_file:                           # <-- Adicione estas linhas
      - ./.env                          # <-- para carregar as variáveis
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - reparai-net

volumes:
  db_data:

networks:
  reparai-net:
    driver: bridge