services:
  db:
    image: mysql:8.0
    restart: always
    # We don't need to expose the port to the host machine unless you
    # want to connect from your local computer with a tool like DBeaver.
    # It's slightly more secure to keep it internal.
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: reparaai
      MYSQL_ROOT_PASSWORD: senha
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reparai-net
    # This block tells Docker to wait until MySQL is ready for connections
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

  backend:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db: # <-- Change this to the new format
        condition: service_healthy # <-- Wait for the health check to pass
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - reparai-net

volumes:
  db_data:

networks:
  reparai-net:
    driver: bridge