version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: reparai-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reparai_db
      MYSQL_USER: reparai
      MYSQL_PASSWORD: reparai
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reparai-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reparai-backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: reparai
      DB_PASSWORD: reparai
      DB_NAME: reparai_db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - reparai-net

volumes:
  db_data:

networks:
  reparai-net:
    driver: bridge
