# ReparaAi/docker-compose.yml

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: reparaai
      MYSQL_ROOT_PASSWORD: senha
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reparai-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - reparai-net

  # --- NOSSO NOVO SERVIÇO DE FRONTEND ---
  frontend:
    build:
      context: ./frontend # 1. Constrói a imagem usando o Dockerfile da pasta /frontend
    restart: always
    ports:
      - "5174:5173" # 2. Mapeia a porta 5174 da sua máquina para a porta 5173 do contêiner
    volumes:
      - ./frontend:/usr/src/app # 3. Mapeia o código local para que o hot-reload funcione
      - /usr/src/app/node_modules
    networks:
      - reparai-net
    depends_on:
      - backend # 4. Garante que o frontend só suba depois do backend

volumes:
  db_data:

networks:
  reparai-net:
    driver: bridge
